name: "zillow_research"
version: "2.0.0"
config-version: 2

profile: "zillow_research"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zillow_research:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: table
      +schema: int
    marts:
      +materialized: table
      +schema: mart

vars:
  source_database: "zillow_research"
  source_schema: "raw_data"
  dbt_utils_dispatch_list: ["dbt_utils"]
