name: "zillow_research"
version: "2.0.0"
config-version: 2

profile: "zillow_research"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  source_database: "zillow_research"
  dbt_utils_dispatch_list: ["dbt_utils"]
