name: "zillow_research"
version: "2.0.0"
config-version: 2

profile: "zillow_research"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zillow_research:
    staging:
      +materialized: view
      +schema: stg
    intermediate:
      +materialized: table
      +schema: int
    marts:
      +materialized: table
      +schema: mart

seeds:
  zillow_research:
    +schema: raw_data
    region_home_values_raw:
      +column_types:
        RegionID: integer
        SizeRank: integer
        RegionName: varchar
        RegionType: varchar
        StateName: varchar
    region_home_values_smooth:
      +column_types:
        RegionID: integer
        SizeRank: integer
        RegionName: varchar
        RegionType: varchar
        StateName: varchar
    region_home_values_tiers:
      +column_types:
        RegionID: integer
        SizeRank: integer
        RegionName: varchar
        RegionType: varchar
        StateName: varchar
    region_home_values_property_types:
      +column_types:
        RegionID: integer
        SizeRank: integer
        RegionName: varchar
        RegionType: varchar
        StateName: varchar
    region_home_value_forecasts_raw:
      +column_types:
        RegionID: integer
        SizeRank: integer
        RegionName: varchar
        RegionType: varchar
        StateName: varchar
    region_home_value_forecasts_smooth:
      +column_types:
        RegionID: integer
        SizeRank: integer
        RegionName: varchar
        RegionType: varchar
        StateName: varchar
    region_rentals:
      +column_types:
        RegionID: integer
        SizeRank: integer
        RegionName: varchar
        RegionType: varchar
        StateName: varchar
    region_renter_demand:
      +column_types:
        RegionID: integer
        SizeRank: integer
        RegionName: varchar
        RegionType: varchar
        StateName: varchar

vars:
  source_database: "zillow_research"
  source_schema: "raw_data"
