name: "zillow_research"
version: "2.0.0"
config-version: 2

profile: "zillow_research"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zillow_research:
    staging:
      +materialized: view
      stg_region_home_value_forecasts:
      stg_region_home_values:
      stg_region_rentals:
      stg_region_renter_demand:

    intermediate:
      +materialized: table
      int_region_home_value_forecasts:
      int_region_home_values:
      int_region_rentals:
      int_region_renter_demand:

    marts:
      +materialized: table
      marts_region_home_values:
      marts_region_rental_prices:
      mart_region_price_to_rent_ratio:
      regions:

vars:
  source_database: "zillow_research"
  dbt_utils_dispatch_list: ["dbt_utils"]
