# dbt_project.yml

name: "zillow_research"
version: "1.0.0"
config-version: 2

profile: "zillow_research"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  zillow_research:
    home_values_by_city:
      +materialized: table
    rentals_by_city:
      +materialized: table
    cities:
      +materialized: table
    city_metrics:
      +materialized: table
    states:
      +materialized: table
    metros:
      +materialized: table

vars:
  source_database: "zillow_research"
  source_schema: "public"
