sources:
  - name: raw
    tables:
      - name: region_home_value_forecasts
      - name: region_home_values
      - name: region_rentals
      - name: region_renter_demand
      - name: region_home_values_property_types
      - name: region_home_values_tiers
