version: 2

sources:
  - name: zillow
    database: "{{ var('source_database') }}"
    schema: "{{ var('source_schema') }}"
    tables:
      - name: home_values_by_city
        description: "Zillow Home Value Index (ZHVI) data for cities downloaded from https://www.zillow.com/research/data/"
      - name: rentals_by_city
        description: "Zillow Observed Rent Index (ZORI) data for cities downloaded from https://www.zillow.com/research/data/"
